# Generated by Django 3.2 on 2022-08-05 12:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_img')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projectapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the project', max_length=200)),
                ('project_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming'), ('Complated', 'Complated')], max_length=10)),
                ('thumnail_image', models.ImageField(upload_to='project_img-thumnails')),
                ('location', models.TextField(blank=True, help_text='write loaction about your project', null=True)),
                ('apartment_type', models.TextField(blank=True, help_text='type of apartments -->example:12 storey luxury 4 bedroom apartments', max_length=500, null=True)),
                ('availability', models.CharField(blank=True, help_text='Sale complete/or not', max_length=200, null=True)),
                ('apartment_size', models.IntegerField(blank=True, help_text='apartment_size in sft', null=True)),
                ('total_apartments', models.IntegerField(blank=True, help_text='how many apartment--->example:20/10 etc', null=True)),
                ('categories', models.ForeignKey(help_text='name of the project category', on_delete=django.db.models.deletion.CASCADE, to='projectapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, help_text='upload images for project', null=True, upload_to='file_upload')),
                ('text', models.CharField(help_text='text must be in 255 character', max_length=255)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
        ),
    ]
