# Generated by Django 3.2 on 2022-09-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming'), ('Completed', 'Completed')], max_length=10),
        ),
    ]
